server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://registry:1111/eureka/
spring:
  application:
     name: api-gateway
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
zuul:
  routes:
    articles-service:
      path: /api/articles-services/**
      sensitive-headers: Cookie, Set-Cookie
    auth-server:
      path: /api/auth-server/**
      sensitive-headers: Cookie, Set-Cookie
    cotizador-service:
      path: /api/cotizador-service/**
      sensitive-headers: Cookie, Set-Cookie
    flow-service:
      path: /api/flow-service/**
      sensitive-headers: Cookie, Set-Cookie
    form-service:
      path: /api/form-service/**
      sensitive-headers: Cookie, Set-Cookie
    prestamos-service:
      path: /api/prestamos-service/**
      sensitive-headers: Cookie, Set-Cookie
    security-service:
      path: /api/security-service/**
      sensitive-headers: Cookie, Set-Cookie
    prestamos-service-new:
      path: /api/prestamos-service-new/**
      sensitive-headers: Cookie, Set-Cookie
    hermes:
      path: /api/hermes/**
      sensitive-headers: Cookie, Set-Cookie
security:
  basic:
    enabled: false
  oauth2:
#    sso:
#      login-path: /login
#      filter-order: 1
    client:
      access-token-uri: ${auth-server.url}/oauth/token
      user-authorization-uri: ${auth-server.url}/oauth/authorize
      client-id: client
      client-secret: secret
      client-authentication-scheme: form
    resource:
      id: api
      token-info-uri: ${auth-server.url}/oauth/check_token
      jwt:
        key-uri: ${auth-server.url}/oauth/token_key
auth-server:
  url : http://auth-server:1116/auth-server

---

spring:
  profiles: docker
auth-server:
  url : http://auth-server:1116/auth-server
eureka:
  instance:
    hostname: ${byte.net.hostname:api-gateway}
    ipAddress: ${byte.net.address}

---

spring:
  application:
    name: api-gateway-bxi
  profiles: docker-bxi
auth-server:
  url : http://auth-server:3002/auth-server
server:
  port: 3003
eureka:
  instance:
    hostname: ${byte.net.hostname:api-gateway}
    ipAddress: ${byte.net.address}

---

spring:
  profiles: no-cookie
eureka:
  instance:
    hostname: ${byte.net.hostname:api-gateway}
    ipAddress: ${byte.net.address}
