server:
  port: ${port:443}
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://registry:1111/eureka/
spring:
  application:
     name: api-gateway
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 120000
ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000
zuul:
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 120000
  routes:
    articles-service:
      path: /api/articles-service/**
      sensitive-headers: Cookie, Set-Cookie
    articles-service-habitat:
      path: /api/articles-service-habitat/**
      sensitive-headers: Cookie, Set-Cookie
    auth-server:
      path: /api/auth-server/**
      sensitive-headers: Cookie, Set-Cookie
    catalog-service:
      path: /api/catalog-service/**
      sensitive-headers: Cookie, Set-Cookie
    clientes-service:
      path: /api/clientes-service/**
      sensitive-headers: Cookie, Set-Cookie
    cobranza-service:
      path: /cobranza-service/**
      sensitive-headers: Cookie, Set-Cookie
    cobranza-service-fallback:
      path: /api/cobranza-service/**
      serviceId: cobranza-service
      sensitive-headers: Cookie, Set-Cookie
    cotizador-service:
      path: /api/cotizador-service/**
      sensitive-headers: Cookie, Set-Cookie
    cotizador-service-habitat:
      path: /api/cotizador-service-habitat/**
      sensitive-headers: Cookie, Set-Cookie
    cotizador-service-habitat2:
      path: /api/cotizador-service-habitat2/**
      sensitive-headers: Cookie, Set-Cookie
    definitions-service:
      path: /api/definitions-service/**
      sensitive-headers: Cookie, Set-Cookie
    transaction-catalog-service:
      path: /api/transaction-catalog-service/**
      sensitive-headers: Cookie, Set-Cookie
    flow-service:
      path: /api/flow-service/**
      url: http://172.16.5.93:5002
      sensitive-headers: Cookie, Set-Cookie
    flow-service-app:
      path: /flow-service/**
      url: http://172.16.5.93:5002
      sensitive-headers: Cookie, Set-Cookie
    flow-service-habitat:
      path: /api/flow-service-habitat/**
      sensitive-headers: Cookie, Set-Cookie
    form-service:
      path: /form-service/**
      sensitive-headers: Cookie, Set-Cookie
    form-service-fallback:
      path: /api/form-service/**
      serviceId: form-service
      sensitive-headers: Cookie, Set-Cookie
    hermes:
      path: /api/hermes/**
      sensitive-headers: Cookie, Set-Cookie
    maintenance-service:
      path: /api/maintenance-service/**
    maintenance-service-habitat:
      path: /api/maintenance-service-habitat/**
      sensitive-headers: Cookie, Set-Cookie
    plataforma-services:
      path: /api/plataforma-services/**
      url: http://cotizador-demo.bytesw.cloud:6001
      sensitive-headers: Cookie, Set-Cookie
    prestamos-service:
      path: /api/prestamos-service/**
      sensitive-headers: Cookie, Set-Cookie
    prestamos-service-new:
      path: /api/prestamos-service-new/**
      sensitive-headers: Cookie, Set-Cookie
    prestamos-service-new-fallback:
      path: /prestamos-service-new/**
      serviceId: prestamos-service-new
      sensitive-headers: Cookie, Set-Cookie
    report-service:
      path: /api/report-service/**
      sensitive-headers: Cookie, Set-Cookie
    resource-service:
      path: /api/resource-service/**
      sensitive-headers: Cookie, Set-Cookie
    search-service:
      path: /api/search-service/**
      sensitive-headers: Cookie, Set-Cookie
    search-service-habitat:
      path: /api/search-service-habitat/**
      sensitive-headers: Cookie, Set-Cookie
    security-service:
      path: /api/security-service/**
      sensitive-headers: Cookie, Set-Cookie
    storage-service:
      path: /api/storage-service/**
      url: http://18.220.235.11:3000
    authorization-manager:
       path: /view/manager/**
       service-id: manager
    manager:
      path: /manager/**
      url: http://seguridad-demo.bytesw.cloud.s3-website-us-east-1.amazonaws.com
    plataforma:
      path: /plataforma/**
      url: http://cotizador-legacy.bytesw.cloud.s3-website.us-east-2.amazonaws.com
      sensitive-headers: Origin
    geko:
      path: /geko/**
      url: http://cotizador-geko.bytesw.cloud.s3-website-us-east-1.amazonaws.com
    cobranza-pruebas:
      path: /cobranza-pruebas/**
      url: http://pre-cobranza.s3-website-us-east-1.amazonaws.com
    habitat:
      path: /habitat/**
      url: http://cotizador-habitat.bytesw.cloud.s3-website-us-east-1.amazonaws.com
    habitat-2:
      path: /habitat-2/**
      url: http://cotizador-habitat-2.bytesw.cloud.s3-website-us-east-1.amazonaws.com
    assets:
      path: /assets/**
      url: http://shared-assets-cotizador.bytesw.cloud.s3-website-us-east-1.amazonaws.com
security:
  basic:
    enabled: false
  oauth2:
#    sso:
#      login-path: /login
#      filter-order: 1
    client:
      access-token-uri: ${auth-server.url}/oauth/token
      user-authorization-uri: ${auth-server.url}/oauth/authorize
      client-id: client
      client-secret: secret
      client-authentication-scheme: form
    resource:
      id: api
      token-info-uri: ${auth-server.url}/oauth/check_token
      jwt:
        key-uri: ${auth-server.url}/oauth/token_key
auth-server:
  url : http://auth-server:1116/auth-server

---

spring:
  profiles: docker
auth-server:
  url : http://auth-server:1116/auth-server
eureka:
  instance:
    hostname: ${byte.net.hostname:api-gateway}
    ipAddress: ${byte.net.address}

---

spring:
  application:
    name: api-gateway-bxi
  profiles: docker-bxi
auth-server:
  url : http://auth-server:3002/auth-server
server:
  port: 3003
eureka:
  instance:
    hostname: ${byte.net.hostname:api-gateway}
    ipAddress: ${byte.net.address}

---

spring:
  profiles: no-cookie
eureka:
  instance:
    hostname: ${byte.net.hostname:api-gateway}
    ipAddress: ${byte.net.address}
