server:
  port: 1116
  context-path: /auth-server
eureka:
  instance:
    statusPageUrlPath: /auth-server/info
    healthCheckUrlPath: /auth-server/health
    preferIpAddress: true
    metadata-map:
      management.context-path: /auth-server
  client:
    serviceUrl:
      defaultZone: http://registry:1111/eureka/
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://${db.local.host:XXXXX}:${db.local.port:3306}/${db.local.schema:seguridad}
    username: ${db.local.user:username}
    password: ${db.local.password:password}
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 10
      min-idle: 15
      max-idle: 20
      max-active: 30
      test-on-borrow: true
      remove-abandoned: true
      remove-abandoned-timeout: 35
      validation-query: select 1
      validation-interval: 30000
      time-between-eviction-runs-millis: 40000
      min-evictable-idle-time-millis: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: api
      token-info-uri: ${auth-server.url}/oauth/check_token
      jwt:
        key-uri: ${auth-server.url}/oauth/token_key
      filter-order: 3
auth-server:
  url: http://auth-server:1116/auth-server
  access-token-validity-seconds: 300000
  refresh-token-validity-seconds: 600000
  authentication:
    enabled: true
    failed-login-attempts: 3
    days-validity-password: 10
    user-inactivity-days: 10
  jwt:
    keystore: auth-server.jks
    storepass: auth-server
    alias: auth-alias
  iseries:
    enabled: false
    host: ${db.core.host:XXXXXXX}
    user: ${db.core.user:XXXXXXX}
    password: ${db.core.password:XXXXXXX}
liquibase:
  context: production

---

spring:
  profiles: docker
eureka:
  instance:
    hostname: ${byte.net.hostname:auth-server}
    ipAddress: ${byte.net.address}