server:
  port: 5002
  context-path: /v1
eureka:
  instance:
    statusPageUrlPath: /v1/info
    healthCheckUrlPath: /v1/health
    preferIpAddress: true
    metadata-map:
      management.context-path: /v1
  client:
    serviceUrl:
      defaultZone: http://registry:1111/eureka/
spring:
  data:
    neo4j:
      uri: bolt://${db.host:localhost}
      username: ${db.user:neo4j}
      password: ${db.password:toor}
  application:
    name: flow-service
security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: api
      token-info-uri: ${auth-server.url}/oauth/check_token
      jwt:
        key-uri: ${auth-server.url}/oauth/token_key
logging:
  level:
    org.hibernate: INFO
byte:
  swagger:
    api:
      title: Flow Service
      description: Documentacion API REST para flujos
      terms-of-service-url: http://www.bytesw.com
      license: Byte
      license-url: http://www.bytesw.com
      version: 1.0.0
      paths:
        - /flow.*

---

spring:
  profiles: docker
eureka:
  instance:
    hostname: ${byte.net.hostname:flow-service}
    ipAddress: ${byte.net.address}
  client:
    serviceUrl:
      defaultZone: http://registry:1111/eureka/
auth-server:
  url : http://auth-server:1116/auth-server