server:
  port: 5005
  context-path: /v1
eureka:
  instance:
    statusPageUrlPath: /v1/info
    healthCheckUrlPath: /v1/health
    preferIpAddress: true
    metadata-map:
      management.context-path: /v1
  client:
    serviceUrl:
      defaultZone: http://registry:1111/eureka/
spring:
  application:
    name: prestamos-service
  datasource:
    url: jdbc:jtds:sqlserver://${db.host:172.16.10.228}:${db.port:1433}/${db.schema:MASESA};
    username: ${db.user:V5APPLSVR}
    password: ${db.password:V5APPLSVR}
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    tomcat:
      test-on-borrow: true
      remove-abandoned: true
      validation-query: select 1
  activemq:
    user: system
    password: manager
    broker-url: tcp://${mq.host:172.16.10.181}:${mq.port:61616}
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.type: trace

logging:
  level:
    org:
      hibernate:
        type: trace
        sql: trace
security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: api
      token-info-uri: ${auth-server.url}/oauth/check_token
      jwt:
        key-uri: ${auth-server.url}/oauth/token_key
auth-server:
  url : http://auth-server:1116/auth-server
web-app:
    jndi:
      as400-auth: 172.16.10.240
      as400-host: 172.16.10.240
      as400-user: PLATAFORMA
      as400-pass: PLATAFORMA
    queue:
      lib: MACARTDAT
      time-out: 60

byte:
  swagger:
    api:
      title: Prestamos Service
      description: Documentacion API REST para el modulo de prestamos
      terms-of-service-url: http://www.bytesw.com
      license: Byte
      license-url: http://www.bytesw.com
      version: 1.0.0
      paths:
        - /prestamos.*
        - /productos.*
  queue:
    queuetrxi: ${mq.inputtrx:NOMBREDELACOLA}

---

spring:
  profiles: docker
eureka:
  instance:
    hostname: ${byte.net.hostname:prestamos-service}
    ipAddress: ${byte.net.address}
  client:
    serviceUrl:
      defaultZone: http://registry:1111/eureka/
auth-server:
  url : http://auth-server:1116/auth-server