server:
  port: 1111
  
eureka:
  instance:
    preferIpAddress: true
    hostname: ${ip.address}
    ipAddress: ${ip.address}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://registry:${server.port}/eureka/
spring:
  thymeleaf:
    enabled: false 
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:1111/eureka/ 
      
---
spring:
  profiles: docker-bxi
server:
  port: 3004
